INSERT INTO problems
(id, title, slug, description, constraints, examples, difficulty, topic, supported_languages, starter_code)
VALUES

(gen_random_uuid(), 'Reverse String', 'reverse-string',
'Given a string, return the reversed string.',
'The string contains printable characters.',
'[{"input":"hello","output":"olleh"}]'::jsonb,
'Easy', 'Strings',
ARRAY['python','javascript','java','cpp'],
'{"python":"def reverse_string(s):\n    pass","javascript":"function reverseString(s) {\n}","java":"class Solution { public String reverseString(String s) { return \"\"; }}","cpp":"#include <string>\nusing namespace std;\nstring reverseString(string s) { return \"\"; }"}'::jsonb),

(gen_random_uuid(), 'Valid Palindrome', 'valid-palindrome',
'Given a string, determine whether it reads the same forward and backward.',
'Ignore case and non-alphanumeric characters.',
'[{"input":"A man, a plan, a canal: Panama","output":"true"}]'::jsonb,
'Easy', 'Strings',
ARRAY['python','javascript','java','cpp'],
'{"python":"def is_palindrome(s):\n    pass","javascript":"function isPalindrome(s) {\n}","java":"class Solution { public boolean isPalindrome(String s) { return false; }}","cpp":"#include <string>\nusing namespace std;\nbool isPalindrome(string s) { return false; }"}'::jsonb),

(gen_random_uuid(), 'Maximum Subarray', 'maximum-subarray',
'Given an integer array, find the contiguous subarray with the largest sum.',
'The array contains at least one integer.',
'[{"input":"[-2,1,-3,4,-1,2,1,-5,4]","output":"6"}]'::jsonb,
'Medium', 'Arrays',
ARRAY['python','javascript','java','cpp'],
'{"python":"def max_subarray(nums):\n    pass","javascript":"function maxSubarray(nums) {\n}","java":"class Solution { public int maxSubArray(int[] nums) { return 0; }}","cpp":"#include <vector>\nusing namespace std;\nint maxSubArray(vector<int> nums) { return 0; }"}'::jsonb),

(gen_random_uuid(), 'Merge Sorted Arrays', 'merge-sorted-arrays',
'Given two sorted arrays, return one sorted array containing all elements.',
'Both arrays are sorted in ascending order.',
'[{"input":"[1,3,5] [2,4,6]","output":"[1,2,3,4,5,6]"}]'::jsonb,
'Easy', 'Arrays',
ARRAY['python','javascript','java','cpp'],
'{"python":"def merge_sorted_arrays(a, b):\n    pass","javascript":"function mergeSortedArrays(a, b) {\n}","java":"class Solution { public int[] mergeSortedArrays(int[] a, int[] b) { return new int[0]; }}","cpp":"#include <vector>\nusing namespace std;\nvector<int> mergeSortedArrays(vector<int> a, vector<int> b) { return {}; }"}'::jsonb),

(gen_random_uuid(), 'Valid Parentheses', 'valid-parentheses',
'Given a string containing brackets, determine whether the brackets are correctly balanced.',
'The string contains only parentheses, brackets, and braces.',
'[{"input":"({[]})","output":"true"}]'::jsonb,
'Easy', 'Stack',
ARRAY['python','javascript','java','cpp'],
'{"python":"def is_valid_parentheses(s):\n    pass","javascript":"function isValidParentheses(s) {\n}","java":"class Solution { public boolean isValid(String s) { return false; }}","cpp":"#include <string>\nusing namespace std;\nbool isValid(string s) { return false; }"}'::jsonb),

(gen_random_uuid(), 'First Unique Character', 'first-unique-character',
'Given a string, return the index of the first character that appears only once.',
'Return -1 if every character repeats.',
'[{"input":"leetcode","output":"0"}]'::jsonb,
'Easy', 'Hashing',
ARRAY['python','javascript','java','cpp'],
'{"python":"def first_unique_character(s):\n    pass","javascript":"function firstUniqueCharacter(s) {\n}","java":"class Solution { public int firstUniqChar(String s) { return -1; }}","cpp":"#include <string>\nusing namespace std;\nint firstUniqueCharacter(string s) { return -1; }"}'::jsonb),

(gen_random_uuid(), 'Fibonacci Number', 'fibonacci-number',
'Given n, return the nth Fibonacci number.',
'0 <= n <= 30.',
'[{"input":"10","output":"55"}]'::jsonb,
'Easy', 'Dynamic Programming',
ARRAY['python','javascript','java','cpp'],
'{"python":"def fibonacci(n):\n    pass","javascript":"function fibonacci(n) {\n}","java":"class Solution { public int fib(int n) { return 0; }}","cpp":"int fibonacci(int n) { return 0; }"}'::jsonb),

(gen_random_uuid(), 'Climbing Stairs', 'climbing-stairs',
'You are climbing a staircase. Each time you can climb one or two steps. Return the number of distinct ways to reach the top.',
'1 <= n <= 45.',
'[{"input":"5","output":"8"}]'::jsonb,
'Easy', 'Dynamic Programming',
ARRAY['python','javascript','java','cpp'],
'{"python":"def climb_stairs(n):\n    pass","javascript":"function climbStairs(n) {\n}","java":"class Solution { public int climbStairs(int n) { return 0; }}","cpp":"int climbStairs(int n) { return 0; }"}'::jsonb),

(gen_random_uuid(), 'Best Time to Buy and Sell Stock', 'best-time-to-buy-and-sell-stock',
'Given daily stock prices, find the maximum profit from one buy and one sell.',
'You must buy before you sell.',
'[{"input":"[7,1,5,3,6,4]","output":"5"}]'::jsonb,
'Easy', 'Arrays',
ARRAY['python','javascript','java','cpp'],
'{"python":"def max_profit(prices):\n    pass","javascript":"function maxProfit(prices) {\n}","java":"class Solution { public int maxProfit(int[] prices) { return 0; }}","cpp":"#include <vector>\nusing namespace std;\nint maxProfit(vector<int> prices) { return 0; }"}'::jsonb),

(gen_random_uuid(), 'Reverse Linked List', 'reverse-linked-list',
'Given the head of a singly linked list, reverse the list and return the new head.',
'The list may be empty.',
'[{"input":"1 -> 2 -> 3 -> 4","output":"4 -> 3 -> 2 -> 1"}]'::jsonb,
'Medium', 'Linked List',
ARRAY['python','javascript','java','cpp'],
'{"python":"def reverse_list(head):\n    pass","javascript":"function reverseList(head) {\n}","java":"class Solution { public ListNode reverseList(ListNode head) { return null; }}","cpp":"struct ListNode { int val; ListNode* next; };\nListNode* reverseList(ListNode* head) { return nullptr; }"}'::jsonb);

